apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  inputs:
    resources:
      - name: docker-source
        type: git
    params:
      - name: pathToDockerFile
        default: /workspace/docker-source/Dockerfile
      - name: pathToContext
        default: /workspace/docker-source
  outputs:
    resources:
      - name: docker-image
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.pathToDockerFile}
        - --destination=${outputs.resources.docker-image.url}
        - --context=${inputs.params.pathToContext}
      env:
        - name: "DOCKER_CONFIG"
          value: "/builder/home/.docker/"
